version: '3'
services:
  app:
    build: ./app
    container_name: app
    restart: always
    # ports:
    #   - '5000:5000'
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
